export const actions = {
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  SELECTED_ID: "SELECTED_ID",
  REMOVE_SELECTED_ID: "REMOVE_SELECTED_ID",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
};
